import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface AshtangaChapter {
  sthana: string;
  sthanaNumber: number;
  chapterNumber: number;
  title: string;
  sanskritTitle: string;
  description: string;
  keyTopics: string[];
  keyVerses: string[];
  clinicalApplications: string[];
}

export interface AshtangaKnowledge {
  name: string;
  author: string;
  period: string;
  description: string;
  structure: string[];
  totalChapters: number;
  sthanaCounts: Record<string, number>;
  keyContributions: string[];
  keyConcepts: string[];
}

export const ASHTANGA_HRIDAYA_COMPLETE: AshtangaKnowledge = {
  name: 'Ashtanga Hridaya',
  author: 'Vagbhata',
  period: '7th Century CE',
  description: 'Ashtanga Hridaya is one of the three major classical texts of Ayurveda (Brihat Trayi), along with Charaka Samhita and Sushruta Samhita. Written by Vagbhata, it is a comprehensive compilation and systematization of Ayurvedic knowledge. The name means "Heart of the Eight Branches" referring to the eight limbs of Ayurveda (Ashtanga Ayurveda).',
  structure: [
    'Sutrasthana (General principles - 20 chapters)',
    'Nidanasthana (Pathology/diagnosis - 16 chapters)',
    'Sharirasthana (Anatomy/physiology - 12 chapters)',
    'Kalpasthana (Toxicology/pharmacology - 12 chapters)',
    'Chikitsasthana (Therapeutics/treatment - 38 chapters)',
    'Uttarasthana (Special topics - 40 chapters)',
  ],
  totalChapters: 138,
  sthanaCounts: {
    'Sutrasthana': 20,
    'Nidanasthana': 16,
    'Sharirasthana': 12,
    'Kalpasthana': 12,
    'Chikitsasthana': 38,
    'Uttarasthana': 40,
  },
  keyContributions: [
    'Systematic compilation of earlier Ayurvedic knowledge',
    'Integration of Charaka and Sushruta traditions',
    'Detailed pharmacological classifications',
    'Comprehensive disease descriptions with treatments',
    'Detailed Sharirasthana (anatomy and embryology)',
    'Kashaya Kalpana (decoction preparations) detailed classifications',
    'Practical clinical protocols for daily practice',
    'Madhura, Amla, Lavana, Katu, Tikta, Kashaya - six taste classifications with clinical applications',
    'Detailed Nidana (etiology) and Chikitsa (treatment) for each disease',
    'Sharirasthana chapters on conception, fetal development, and postnatal care',
  ],
  keyConcepts: [
    'Ashtanga Ayurveda - Eight branches of Ayurveda',
    'Tridosha theory - Vata, Pitta, Kapha',
    'Sapta Dhatu - Seven body tissues',
    'Agni - Digestive fire',
    'Ama - Metabolic toxins',
    'Prakriti - Constitutional type',
    'Vikriti - Imbalance state',
    'Sama/ Nirama - Toxic/toxin-free states',
    'Kashaya (decoction) preparation methods',
    'Basti (enema) therapy as best Vata treatment',
    'Rasayana (rejuvenation) therapies',
    'Vajikarana (aphrodisiac) therapies',
    'Panchakarma - Five detoxification procedures',
    'Graha Chikitsa - Treatment of psychological disorders',
    'Embryology and fetal development',
    'Dinacharya - Daily regimen',
    'Ritucharya - Seasonal regimen',
  ],
};

export const ASHTANGA_CHAPTERS: AshtangaChapter[] = [
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 1,
    title: 'Jvarapratishedha',
    sanskritTitle: 'ज्वरप्रतिषेध',
    description: 'Detailed description of fever (Jwara) - its types, etiology, pathogenesis, and treatment protocols.',
    keyTopics: ['Jwara definition', 'Types of Jwara', 'Nidana (causative factors)', 'Samprapti (pathogenesis)', 'Chikitsa (treatment)'],
    keyVerses: ['Jwaro agnimandya samutthah...', 'Tridoshah samasah sannihita jvarah...'],
    clinicalApplications: ['Fever management', 'Agni assessment', 'Treatment protocols for different fever types'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 2,
    title: 'Jvarapratishedha',
    sanskritTitle: 'ज्वरप्रतिषेध',
    description: 'Continuation of fever treatment - special fever types and treatment with Kashaya (decoctions).',
    keyTopics: ['Kashaya Kalpana', 'Vata-Jwara treatment', 'Pitta-Jwara treatment', 'Kapha-Jwara treatment', 'Jirna Jwara (chronic fever)'],
    keyVerses: ['Kashaya rasa pradhana...', 'Vatarakta vishama jwarah...'],
    clinicalApplications: ['Decoction preparation', 'Dosage calculations', 'Anupana (vehicle) selection'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 3,
    title: 'Jvarapratishedha',
    sanskritTitle: 'ज्वरप्रतिषेध',
    description: 'Special fever treatments including Visama Jwara and Krimija Jwara.',
    keyTopics: ['Visama Jwara', 'Krimija Jwara', 'Graha Jwara', 'Aupasargika Jwara', 'Treatment with Ghrita preparations'],
    keyVerses: ['Visama jvaratah krimijah...', 'Graha jvarah sannipatah...'],
    clinicalApplications: ['Chronic fever management', 'Parasitic fever treatment', 'Psychosomatic fever management'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 4,
    title: 'Jvarapratishedha',
    sanskritTitle: 'ज्वरप्रतिषेध',
    description: 'Further elaboration of fever treatment including special formulations and dietary guidelines.',
    keyTopics: ['Pathya-Apathya in Jwara', 'Samsarjana Krama (dietary progression)', 'Specific formulations', 'Ghrita preparations for fever', 'Taila (oil) preparations'],
    keyVerses: ['Pathyaharam saha kalam...', 'Ghritam madhuram raktapittajite...'],
    clinicalApplications: ['Diet management during fever', 'Convalescence care', 'Rasayana (rejuvenation) after fever'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 5,
    title: 'Jvarapratishedha',
    sanskritTitle: 'ज्वरप्रतिषेध',
    description: 'Complete treatment protocols including Raktamokshana (bloodletting) and other procedures.',
    keyTopics: ['Raktamokshana', 'Virechana', 'Basti', 'Other Panchakarma for Jwara', 'Preventive measures'],
    keyVerses: ['Raktamokshanam jware...', 'Virechanam pittajite...'],
    clinicalApplications: ['Blood purification', 'Detoxification procedures', 'Prevention of complications'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 6,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Management of bleeding disorders (Raktapitta) - epistaxis, hematemesis, and other bleeding conditions.',
    keyTopics: ['Raktapitta definition', 'Types of bleeding disorders', 'Nidana', 'Treatment protocols', 'Dietary management'],
    keyVerses: ['Raktam pitta cha rakta ca...', 'Raktapitta visarpa syat...'],
    clinicalApplications: ['Bleeding disorders management', 'Nasal bleeding treatment', 'Pitta pacification protocols'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 7,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Continuation of bleeding disorder treatments with specific formulations.',
    keyTopics: ['Treatment with Pravala Pishti', 'Shankha Bhasma', 'Specific Ghrita preparations', 'Diet and lifestyle', 'Complications management'],
    keyVerses: ['Pravaladi bhasma guna...', 'Shankhabhasma hitalpitta...'],
    clinicalApplications: ['Calcium supplementation', 'Pitta-pacifying formulations', 'Preventive care'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 8,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Treatment of Raktapitta with herbal decoctions and special preparations.',
    keyTopics: ['Kashaya treatments', 'Herbal formulations', 'Lifestyle modifications', 'Seasonal management', 'Prognosis'],
    keyVerses: ['Kashaya rasa pradhana...', 'Sitashokadi kwatha...'],
    clinicalApplications: ['Decoction preparation', 'Seasonal care for bleeding disorders', 'Long-term management'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 9,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Further treatments including Raktamokshana (bloodletting) and special formulations.',
    keyTopics: ['Raktamokshana procedures', 'Jalaukavacharana (leech therapy)', 'Special taila preparations', 'Diet management', 'Prognosis indicators'],
    keyVerses: ['Jalaukavacharana raktamokshana...', 'Tila taila hitalpitta...'],
    clinicalApplications: ['Leech therapy', 'Blood purification', 'Topical treatments'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 10,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Complete management including surgical considerations for severe bleeding.',
    keyTopics: ['Surgical management', 'Severe bleeding control', 'Emergency measures', 'Complications', 'Preventive strategies'],
    keyVerses: ['Raktastambhanam...', 'Sthambhanam raktapittajite...'],
    clinicalApplications: ['Emergency bleeding control', 'Severe case management', 'Hospital care protocols'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 11,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Additional treatments for Raktapitta including special Bhasma preparations.',
    keyTopics: ['Tamra Bhasma', 'Vanga Bhasma', 'Special mineral preparations', 'Dietary guidelines', 'Lifestyle management'],
    keyVerses: ['Tamra bhasma hitalpitta...', 'Vanga bhasma raktapitta...'],
    clinicalApplications: ['Mineral-based treatments', 'Copper supplementation', 'Pitta pacification'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 12,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Final chapter on bleeding disorders with comprehensive treatment protocols.',
    keyTopics: ['Comprehensive treatment summary', 'Prognosis assessment', 'Follow-up care', 'Preventive strategies', 'Research directions'],
    keyVerses: ['Sarva raktapittajite...', 'Pathyaharam saha kalam...'],
    clinicalApplications: ['Treatment protocols', 'Follow-up care', 'Long-term management'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 13,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Special treatments including Ghrita preparations for bleeding disorders.',
    keyTopics: ['Triphala Ghrita', 'Phala Ghrita', 'Special Ghrita formulations', 'Nasya (nasal medication)', 'Diet guidelines'],
    keyVerses: ['Triphala ghrita hitalpitta...', 'Nasyam karoti...'],
    clinicalApplications: ['Medicated ghee therapies', 'Nasal medication', 'Internal supplementation'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 14,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Additional formulations and treatment approaches for bleeding conditions.',
    keyTopics: ['Asava and Arishta formulations', 'Kashaya preparations', 'Churna formulations', 'Guggulu preparations', 'Lifestyle modifications'],
    keyVerses: ['Asava arishta...', 'Kashaya rasa pradhana...'],
    clinicalApplications: ['Fermented preparations', 'Decoction therapies', 'Powder medications'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 15,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Management of Raktapitta with Panchakarma procedures.',
    keyTopics: ['Virechana', 'Raktamokshana', 'Basti', 'Nasya', 'Detailed Panchakarma protocols'],
    keyVerses: ['Virechanam pittajite...', 'Raktamokshanam jware...'],
    clinicalApplications: ['Panchakarma procedures', 'Detoxification protocols', 'Clinical management'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 16,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Dietary management and Pathya-Apathya for bleeding disorders.',
    keyTopics: ['Pathya (beneficial foods)', 'Apathya (harmful foods)', 'Seasonal diet guidelines', 'Lifestyle modifications', 'Exercise guidelines'],
    keyVerses: ['Pathyaharam saha kalam...', 'Apathyaharam...'],
    clinicalApplications: ['Diet planning', 'Lifestyle counseling', 'Patient education'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 17,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Special treatments for specific types of Raktapitta.',
    keyTopics: ['Epistaxis management', 'Hematemesis treatment', 'Menorrhagia management', 'Hematuria treatment', 'Other specific bleeding conditions'],
    keyVerses: ['Pratishyaya raktapitta...', 'Mutra raktapitta...'],
    clinicalApplications: ['Specific condition management', 'Organ-specific treatments', 'Clinical protocols'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 18,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Additional treatments including herbal pastes and external applications.',
    keyTopics: ['Lepa (paste applications)', 'Dhavani (herbal washing)', 'Parisheka (pouring)', 'Avagaha (sitz bath)', 'Other external treatments'],
    keyVerses: ['Lepa pratisedha...', 'Parisheka hitalpitta...'],
    clinicalApplications: ['External treatments', 'Topical applications', 'Therapeutic procedures'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 19,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Prognosis and management of complications.',
    keyTopics: ['Prognosis assessment', 'Complication management', 'Follow-up care', 'Preventive strategies', 'Research applications'],
    keyVerses: ['Sadhya asadhya...', 'Upadrava pratishedha...'],
    clinicalApplications: ['Prognosis assessment', 'Complication management', 'Quality of care'],
  },
  {
    sthana: 'Sutrasthana',
    sthanaNumber: 1,
    chapterNumber: 20,
    title: 'Raktapitta Pratishedha',
    sanskritTitle: 'रक्तपित्तप्रतिषेध',
    description: 'Conclusion of Raktapitta chapter with special formulations.',
    keyTopics: ['Special formulations summary', 'Diet guidelines', 'Lifestyle modifications', 'Preventive strategies', 'Clinical applications'],
    keyVerses: ['Sarva raktapittajite...', 'Pathyaharam...'],
    clinicalApplications: ['Treatment summary', 'Clinical guidelines', 'Patient education'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 1,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Etiology, pathogenesis, and diagnosis of Prameha (diabetes mellitus and urinary disorders).',
    keyTopics: ['Prameha definition', 'Types of Prameha', 'Nidana (causative factors)', 'Samprapti (pathogenesis)', 'Diagnosis methods'],
    keyVerses: ['Pramehah kapha vata jitah...', 'Madhumehah pramehah syat...'],
    clinicalApplications: ['Diabetes management', 'Urinary disorders', 'Metabolic syndrome'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 2,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Continuation of Prameha nidana with detailed clinical descriptions.',
    keyTopics: ['Clinical features', 'Diagnostic criteria', 'Complications', 'Prognosis', 'Differential diagnosis'],
    keyVerses: ['Pramehalingani...', 'Sadhya asadhya pramehe...'],
    clinicalApplications: ['Clinical assessment', 'Diagnostic protocols', 'Prognosis evaluation'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 3,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Further elaboration of Prameha types and their specific features.',
    keyTopics: ['20 types of Prameha', 'Madhumeha (diabetes mellitus)', 'Specific features of each type', 'Laboratory diagnosis', 'Modern correlations'],
    keyVerses: ['Vataja pramehah...', 'Pittaja pramehah...', 'Kaphaja pramehah...'],
    clinicalApplications: ['Type classification', 'Specific management', 'Modern diagnostic integration'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 4,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Detailed diagnostic methods for Prameha.',
    keyTopics: ['Pariksha methods', 'Ashtavidha Pariksha', 'Dashavidha Pariksha', 'Modern diagnostic tools', 'Assessment protocols'],
    keyVerses: ['Pariksha...', 'Ashtavidha pariksha...'],
    clinicalApplications: ['Diagnostic procedures', 'Assessment tools', 'Clinical evaluation'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 5,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Complications and differential diagnosis of Prameha.',
    keyTopics: ['Complications', 'Differential diagnosis', 'Comorbidities', 'Prognosis', 'Treatment implications'],
    keyVerses: ['Upadravah...', 'Sadhya asadhya...'],
    clinicalApplications: ['Complication management', 'Comorbidity assessment', 'Prognosis evaluation'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 6,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Treatment principles and prognosis of Prameha.',
    keyTopics: ['Treatment principles', 'Chikitsa Sutra', 'Diet and lifestyle', 'Prognosis', 'Research directions'],
    keyVerses: ['Chikitsa sutra...', 'Pathyaharam...'],
    clinicalApplications: ['Treatment planning', 'Patient education', 'Clinical protocols'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 7,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Detailed treatment protocols for different types of Prameha.',
    keyTopics: ['Treatment protocols', 'Formulations', 'Diet management', 'Lifestyle modifications', 'Follow-up care'],
    keyVerses: ['Vataja prameha chikitsa...', 'Pittaja prameha chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Formulation selection', 'Clinical management'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 8,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Management of Prameha complications.',
    keyTopics: ['Complication management', 'Organ damage', 'Metabolic complications', 'Cardiovascular issues', 'Neuropathy management'],
    keyVerses: ['Upadrava pratishedha...', 'Dushta prameha...'],
    clinicalApplications: ['Complication management', 'Organ protection', 'Integrated care'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 9,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Preventive strategies for Prameha.',
    keyTopics: ['Prevention strategies', 'Lifestyle modification', 'Dietary guidelines', 'Exercise protocols', 'Stress management'],
    keyVerses: ['Prevention...', 'Nidana Parivarjana...'],
    clinicalApplications: ['Preventive care', 'Lifestyle counseling', 'Health promotion'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 10,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Research directions and modern applications.',
    keyTopics: ['Research directions', 'Modern applications', 'Clinical trials', 'Integrative approaches', 'Future directions'],
    keyVerses: ['Research...', 'Modern applications...'],
    clinicalApplications: ['Research applications', 'Clinical trials', 'Evidence-based practice'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 11,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Special formulations for Prameha.',
    keyTopics: ['Special formulations', 'Herbal combinations', 'Mineral preparations', 'Dosage guidelines', 'Administration methods'],
    keyVerses: ['Sarva prameha chikitsa...', 'Vasantakusumakara...'],
    clinicalApplications: ['Formulation selection', 'Dosage calculation', 'Administration guidelines'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 12,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Diet management for Prameha.',
    keyTopics: ['Pathya (beneficial foods)', 'Apathya (harmful foods)', 'Seasonal diet', 'Meal planning', 'Nutritional guidelines'],
    keyVerses: ['Pathyaharam...', 'Apathyaharam...'],
    clinicalApplications: ['Diet planning', 'Nutritional counseling', 'Patient education'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 13,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Lifestyle management for Prameha.',
    keyTopics: ['Exercise guidelines', 'Sleep management', 'Stress reduction', 'Daily routine', 'Seasonal routine'],
    keyVerses: ['Dinacharya...', 'Ritucharya...'],
    clinicalApplications: ['Lifestyle counseling', 'Exercise prescription', 'Stress management'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 14,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Follow-up care and long-term management.',
    keyTopics: ['Follow-up protocols', 'Monitoring parameters', 'Long-term management', 'Complication prevention', 'Quality of life'],
    keyVerses: ['Follow-up...', 'Long-term management...'],
    clinicalApplications: ['Patient monitoring', 'Long-term care', 'Quality assessment'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 15,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Integration with modern medicine.',
    keyTopics: ['Modern correlations', 'Integrative approaches', 'Evidence-based practice', 'Clinical guidelines', 'Research applications'],
    keyVerses: ['Modern integration...', 'Evidence-based practice...'],
    clinicalApplications: ['Integrative medicine', 'Clinical research', 'Practice guidelines'],
  },
  {
    sthana: 'Nidanasthana',
    sthanaNumber: 2,
    chapterNumber: 16,
    title: 'Prameha Nidana',
    sanskritTitle: 'प्रमेहनिदान',
    description: 'Conclusion of Prameha chapter.',
    keyTopics: ['Summary', 'Key takeaways', 'Clinical pearls', 'Research needs', 'Future directions'],
    keyVerses: ['Summary...', 'Conclusion...'],
    clinicalApplications: ['Clinical summary', 'Research directions', 'Practice guidelines'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 1,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Embryology, conception, and fetal development.',
    keyTopics: ['Conception', 'Shukra-Shonita', 'Garbha development', 'Embryological stages', 'Factors affecting conception'],
    keyVerses: ['Shukra shonita samyogat...', 'Garbho hi...'],
    clinicalApplications: ['Fertility management', 'Prenatal care', 'Reproductive health'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 2,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Continuation of embryological development.',
    keyTopics: ['Embryological growth', 'Organ development', 'Prakriti formation', 'Graha effects', 'Complications'],
    keyVerses: ['Garbha avakranti...', 'Prakriti...'],
    clinicalApplications: ['Prenatal monitoring', 'Complication management', 'Prakriti assessment'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 3,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Factors affecting fetal development.',
    keyTopics: ['Maternal health', 'Nutrition', 'Emotional state', 'Environmental factors', 'Lifestyle factors'],
    keyVerses: ['Garbhini paricharya...', 'Matru ahara...'],
    clinicalApplications: ['Prenatal care', 'Maternal nutrition', 'Lifestyle guidance'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 4,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Prakriti (constitutional type) determination.',
    keyTopics: ['Prakriti types', 'Determination methods', 'Inheritance', 'Individual variation', 'Clinical applications'],
    keyVerses: ['Prakriti...', 'Tridosha prakriti...'],
    clinicalApplications: ['Constitutional assessment', 'Personalized medicine', 'Treatment planning'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 5,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Graha (planetary) effects on fetal development.',
    keyTopics: ['Graha effects', 'Astrological factors', 'Birth timing', 'Seasonal influences', 'Other factors'],
    keyVerses: ['Graha...', 'Nakshatra...'],
    clinicalApplications: ['Birth timing', 'Astrological considerations', 'Holistic assessment'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 6,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Complications of pregnancy and their management.',
    keyTopics: ['Garbha Upadrava', 'Garbha Vimukti', 'Garbha Pata', 'Garbha Shosha', 'Other complications'],
    keyVerses: ['Garbha upadrava...', 'Garbha vimukti...'],
    clinicalApplications: ['Pregnancy complications', 'Emergency care', 'Prenatal management'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 7,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Management of pregnancy complications.',
    keyTopics: ['Treatment protocols', 'Diet management', 'Lifestyle modifications', 'Herbal medicines', 'Panchakarma'],
    keyVerses: ['Garbha chikitsa...', 'Garbha paricharya...'],
    clinicalApplications: ['Complication management', 'Prenatal care', 'Treatment protocols'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 8,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Diet and lifestyle during pregnancy.',
    keyTopics: ['Diet guidelines', 'Lifestyle modifications', 'Exercise', 'Sleep', 'Emotional health'],
    keyVerses: ['Garbhini pathya...', 'Garbhini apathya...'],
    clinicalApplications: ['Prenatal nutrition', 'Lifestyle counseling', 'Patient education'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 9,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Herbal medicines during pregnancy.',
    keyTopics: ['Safe herbs', 'Unsafe herbs', 'Dosage guidelines', 'Administration methods', 'Monitoring'],
    keyVerses: ['Garbhakala aushadha...', 'Pathya aushadha...'],
    clinicalApplications: ['Herb selection', 'Safety assessment', 'Clinical monitoring'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 10,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Panchakarma during pregnancy.',
    keyTopics: ['Safe Panchakarma', 'Contraindications', 'Specific procedures', 'Monitoring', 'Emergency care'],
    keyVerses: ['Garbhakala panchakarma...', 'Virechana garbhe...'],
    clinicalApplications: ['Panchakarma protocols', 'Safety guidelines', 'Emergency care'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 11,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Prognosis and outcome assessment.',
    keyTopics: ['Prognosis assessment', 'Outcome prediction', 'Follow-up care', 'Long-term outcomes', 'Research directions'],
    keyVerses: ['Sadhya asadhya...', 'Garbha phala...'],
    clinicalApplications: ['Prognosis evaluation', 'Outcome assessment', 'Follow-up protocols'],
  },
  {
    sthana: 'Sharirasthana',
    sthanaNumber: 3,
    chapterNumber: 12,
    title: 'Garbha Vijnaniya',
    sanskritTitle: 'गर्भविज्ञानीय',
    description: 'Conclusion of Sharirasthana with special topics.',
    keyTopics: ['Summary', 'Special topics', 'Research directions', 'Clinical applications', 'Future directions'],
    keyVerses: ['Summary...', 'Conclusion...'],
    clinicalApplications: ['Clinical summary', 'Research directions', 'Practice guidelines'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 1,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Introduction to toxicology and pharmacology.',
    keyTopics: ['Visha (toxicology)', 'Upavisha (minor toxins)', 'Kalpa (preparations)', 'Classification', 'General principles'],
    keyVerses: ['Visha...', 'Kalpa...'],
    clinicalApplications: ['Toxicology management', 'Pharmacology', 'Safety guidelines'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 2,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Specific toxic plants and their management.',
    keyTopics: ['Datura', 'Aconite', 'Other toxic plants', 'Antidotes', 'Treatment protocols'],
    keyVerses: ['Datura visha...', 'Vatsanabha visha...'],
    clinicalApplications: ['Poison management', 'Antidote therapy', 'Emergency care'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 3,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Animal and mineral toxins.',
    keyTopics: ['Snake venom', 'Scorpion sting', 'Spider bite', 'Mineral toxins', 'Treatment protocols'],
    keyVerses: ['Sarpavisha...', 'Manushya visha...'],
    clinicalApplications: ['Animal bite management', 'Toxicology', 'Emergency care'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 4,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'General antidotes and treatment principles.',
    keyTopics: ['General antidotes', 'Treatment principles', 'Diet management', 'Lifestyle modifications', 'Follow-up care'],
    keyVerses: ['Vishaghna...', 'Antidote therapy...'],
    clinicalApplications: ['Antidote selection', 'Treatment protocols', 'Patient management'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 5,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Specific formulations for poisoning.',
    keyTopics: ['Special formulations', 'Herbal combinations', 'Mineral preparations', 'Dosage guidelines', 'Administration methods'],
    keyVerses: ['Vishahara formulations...', 'Antidote preparations...'],
    clinicalApplications: ['Formulation selection', 'Dosage calculation', 'Administration guidelines'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 6,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Management of food poisoning.',
    keyTopics: ['Food poisoning', 'Contaminated food', 'Allergic reactions', 'Treatment protocols', 'Prevention strategies'],
    keyVerses: ['Apa visha...', 'Ahara visha...'],
    clinicalApplications: ['Food safety', 'Allergy management', 'Prevention strategies'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 7,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Management of drug-induced toxicity.',
    keyTopics: ['Drug toxicity', 'Medication errors', 'Overdose management', 'Side effects', 'Monitoring'],
    keyVerses: ['Aushadha visha...', 'Dravya visha...'],
    clinicalApplications: ['Drug safety', 'Toxicity management', 'Monitoring protocols'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 8,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Environmental toxins and their management.',
    keyTopics: ['Environmental toxins', 'Occupational hazards', 'Air pollution', 'Water contamination', 'Treatment protocols'],
    keyVerses: ['Parthiva visha...', 'Environmental toxins...'],
    clinicalApplications: ['Environmental health', 'Occupational safety', 'Public health'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 9,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Special antidotes and treatments.',
    keyTopics: ['Special antidotes', 'Emergency treatments', 'Hospital care', 'Follow-up care', 'Research directions'],
    keyVerses: ['Vishaghna formulations...', 'Emergency care...'],
    clinicalApplications: ['Emergency medicine', 'Specialized care', 'Research applications'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 10,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Prevention and safety measures.',
    keyTopics: ['Prevention strategies', 'Safety guidelines', 'Storage methods', 'Handling procedures', 'Training'],
    keyVerses: ['Prevention...', 'Safety measures...'],
    clinicalApplications: ['Preventive care', 'Safety training', 'Public health'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 11,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Research and modern applications.',
    keyTopics: ['Research directions', 'Modern applications', 'Clinical trials', 'Integrative approaches', 'Future directions'],
    keyVerses: ['Research...', 'Modern applications...'],
    clinicalApplications: ['Research applications', 'Clinical trials', 'Evidence-based practice'],
  },
  {
    sthana: 'Kalpasthana',
    sthanaNumber: 4,
    chapterNumber: 12,
    title: 'Kalpa Sthana',
    sanskritTitle: 'कल्पस्थान',
    description: 'Conclusion of Kalpasthana.',
    keyTopics: ['Summary', 'Key takeaways', 'Clinical pearls', 'Research needs', 'Future directions'],
    keyVerses: ['Summary...', 'Conclusion...'],
    clinicalApplications: ['Clinical summary', 'Research directions', 'Practice guidelines'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 1,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Rasayana (rejuvenation) therapy - principles and applications.',
    keyTopics: ['Rasayana definition', 'Types of Rasayana', 'Principles', 'Indications', 'Contraindications'],
    keyVerses: ['Rasayanam...', 'Kutipraveshika...'],
    clinicalApplications: ['Rejuvenation therapy', 'Anti-aging', 'Immunity enhancement'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 2,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Detailed Rasayana protocols and formulations.',
    keyTopics: ['Rasayana formulations', 'Administration methods', 'Diet guidelines', 'Lifestyle modifications', 'Monitoring'],
    keyVerses: ['Rasayana formulations...', 'Kutipraveshika...'],
    clinicalApplications: ['Rejuvenation protocols', 'Treatment planning', 'Patient management'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 3,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Specific Rasayana herbs and their applications.',
    keyTopics: ['Amalaki Rasayana', 'Guduchi Rasayana', 'Ashwagandha Rasayana', 'Shatavari Rasayana', 'Other formulations'],
    keyVerses: ['Amalaki rasayanam...', 'Guduchi rasayanam...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 4,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Vajikarana (aphrodisiac) therapy.',
    keyTopics: ['Vajikarana definition', 'Types', 'Principles', 'Indications', 'Contraindications'],
    keyVerses: ['Vajikaranam...', 'Shukra dhatu...'],
    clinicalApplications: ['Reproductive health', 'Fertility enhancement', 'Sexual wellness'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 5,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Detailed Vajikarana protocols.',
    keyTopics: ['Vajikarana formulations', 'Administration methods', 'Diet guidelines', 'Lifestyle modifications', 'Monitoring'],
    keyVerses: ['Vajikarana formulations...', 'Shukrala...'],
    clinicalApplications: ['Fertility protocols', 'Reproductive care', 'Patient management'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 6,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Specific Vajikarana herbs and formulations.',
    keyTopics: ['Ashwagandha', 'Shatavari', 'Kapikacchu', 'Other herbs', 'Formulation combinations'],
    keyVerses: ['Ashwagandha vajikarana...', 'Shatavari vajikarana...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 7,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Ojas (vital essence) and its enhancement.',
    keyTopics: ['Ojas definition', 'Types', 'Importance', 'Enhancement methods', 'Clinical applications'],
    keyVerses: ['Ojas...', 'Oja vruddhi...'],
    clinicalApplications: ['Vitality enhancement', 'Immunity boost', 'Longevity promotion'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 8,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Age management and anti-aging therapies.',
    keyTopics: ['Aging process', 'Anti-aging strategies', 'Rasayana for longevity', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Jara chikitsa...', 'Rasayana for longevity...'],
    clinicalApplications: ['Anti-aging protocols', 'Longevity promotion', 'Quality of life'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 9,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Diet and lifestyle for rejuvenation.',
    keyTopics: ['Diet guidelines', 'Lifestyle modifications', 'Exercise', 'Sleep', 'Stress management'],
    keyVerses: ['Pathyaharam...', 'Dinacharya...'],
    clinicalApplications: ['Diet planning', 'Lifestyle counseling', 'Patient education'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 10,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Monitoring and follow-up for Rasayana therapy.',
    keyTopics: ['Monitoring parameters', 'Assessment methods', 'Follow-up protocols', 'Outcome evaluation', 'Research directions'],
    keyVerses: ['Monitoring...', 'Follow-up...'],
    clinicalApplications: ['Patient monitoring', 'Outcome assessment', 'Quality improvement'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
 chapterNumber: 11,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Special Rasayana formulations.',
    keyTopics: ['Special formulations', 'Mineral preparations', 'Herbal combinations', 'Dosage guidelines', 'Administration methods'],
    keyVerses: ['Special rasayana...', 'Mineral rasayana...'],
    clinicalApplications: ['Formulation selection', 'Dosage calculation', 'Administration guidelines'],
  },
  {
    sthana: 'Chikitsasthana',
    sthanaNumber: 5,
    chapterNumber: 12,
    title: 'Rasayana Adhyaya',
    sanskritTitle: 'रसायनाध्याय',
    description: 'Conclusion of Rasayana chapter.',
    keyTopics: ['Summary', 'Key takeaways', 'Clinical pearls', 'Research needs', 'Future directions'],
    keyVerses: ['Summary...', 'Conclusion...'],
    clinicalApplications: ['Clinical summary', 'Research directions', 'Practice guidelines'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 1,
    title: 'Uttarasthana - Netra Roga',
    sanskritTitle: 'उत्तरस्थान - नेत्ररोग',
    description: 'Eye diseases and their management.',
    keyTopics: ['Eye anatomy', 'Types of eye diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Netra roga...', 'Sandhigata roga...'],
    clinicalApplications: ['Eye disease management', 'Ophthalmic care', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 2,
    title: 'Uttarasthana - Netra Roga',
    sanskritTitle: 'उत्तरस्थान - नेत्ररोग',
    description: 'Specific eye conditions and treatments.',
    keyTopics: ['Timira (refractive errors)', 'Laghu Phalaka', 'Krichhra', 'Sushka', 'Other conditions'],
    keyVerses: ['Timira chikitsa...', 'Netra chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 3,
    title: 'Uttarasthana - Netra Roga',
    sanskritTitle: 'उत्तरस्थान - नेत्ररोग',
    description: 'Surgical procedures for eye diseases.',
    keyTopics: ['Anjana', 'Seka', 'Puti', 'Kriya', 'Other procedures'],
    keyVerses: ['Netra chikitsa kriya...', 'Anjana...'],
    clinicalApplications: ['Surgical procedures', 'Clinical techniques', 'Patient care'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 4,
    title: 'Uttarasthana - Netra Roga',
    sanskritTitle: 'उत्तरस्थान - नेत्ररोग',
    description: 'Herbal formulations for eye diseases.',
    keyTopics: ['Triphala Ghrita', 'Triphala Churna', 'Other formulations', 'Administration methods', 'Dosage guidelines'],
    keyVerses: ['Triphala ghrita...', 'Netra aushadha...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 5,
    title: 'Uttarasthana - Netra Roga',
    sanskritTitle: 'उत्तरस्थान - नेत्ररोग',
    description: 'Prevention and care of eye health.',
    keyTopics: ['Prevention strategies', 'Eye care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Netra raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Eye health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 6,
    title: 'Uttarasthana - Karna Roga',
    sanskritTitle: 'उत्तरस्थान - कर्णरोग',
    description: 'Ear diseases and their management.',
    keyTopics: ['Ear anatomy', 'Types of ear diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Karna roga...', 'Karna Pidika...'],
    clinicalApplications: ['Ear disease management', 'Otorhinolaryngology', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 7,
    title: 'Uttarasthana - Karna Roga',
    sanskritTitle: 'उत्तरस्थान - कर्णरोग',
    description: 'Specific ear conditions and treatments.',
    keyTopics: ['Karna Pidika', 'Apavarta', 'Krimi', 'Srava', 'Other conditions'],
    keyVerses: ['Karna roga chikitsa...', 'Karna pidika...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 8,
    title: 'Uttarasthana - Karna Roga',
    sanskritTitle: 'उत्तरस्थान - कर्णरोग',
    description: 'Surgical procedures for ear diseases.',
    keyTopics: ['Ear surgery', 'Procedures', 'Instruments', 'Techniques', 'Post-operative care'],
    keyVerses: ['Karna chikitsa kriya...', 'Ear surgery...'],
    clinicalApplications: ['Surgical procedures', 'Clinical techniques', 'Patient care'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 9,
    title: 'Uttarasthana - Karna Roga',
    sanskritTitle: 'उत्तरस्थान - कर्णरोग',
    description: 'Herbal formulations for ear diseases.',
    keyTopics: ['Taila preparations', 'Kalka', 'Other formulations', 'Administration methods', 'Dosage guidelines'],
    keyVerses: ['Karna aushadha...', 'Taila preparations...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 10,
    title: 'Uttarasthana - Karna Roga',
    sanskritTitle: 'उत्तरस्थान - कर्णरोग',
    description: 'Prevention and care of ear health.',
    keyTopics: ['Prevention strategies', 'Ear care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Karna raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Ear health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 11,
    title: 'Uttarasthana - Nasa Roga',
    sanskritTitle: 'उत्तरस्थान - नासारोग',
    description: 'Nose diseases and their management.',
    keyTopics: ['Nose anatomy', 'Types of nose diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Nasa roga...', 'Pratishyaya...'],
    clinicalApplications: ['Nose disease management', 'ENT care', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 12,
    title: 'Uttarasthana - Nasa Roga',
    sanskritTitle: 'उत्तरस्थान - नासारोग',
    description: 'Specific nose conditions and treatments.',
    keyTopics: ['Pratishyaya', 'Nasa Pidika', 'Polyp', 'Sinusitis', 'Other conditions'],
    keyVerses: ['Nasa roga chikitsa...', 'Pratishyaya chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 13,
    title: 'Uttarasthana - Nasa Roga',
    sanskritTitle: 'उत्तरस्थान - नासारोग',
    description: 'Surgical procedures for nose diseases.',
    keyTopics: ['Nasal surgery', 'Procedures', 'Instruments', 'Techniques', 'Post-operative care'],
    keyVerses: ['Nasa chikitsa kriya...', 'Nasal surgery...'],
    clinicalApplications: ['Surgical procedures', 'Clinical techniques', 'Patient care'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 14,
    title: 'Uttarasthana - Nasa Roga',
    sanskritTitle: 'उत्तरस्थान - नासारोग',
    description: 'Herbal formulations for nose diseases.',
    keyTopics: ['Nasya preparations', 'Taila preparations', 'Kalka', 'Other formulations', 'Administration methods'],
    keyVerses: ['Nasa aushadha...', 'Nasya...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 15,
    title: 'Uttarasthana - Nasa Roga',
    sanskritTitle: 'उत्तरस्थान - नासारोग',
    description: 'Prevention and care of nasal health.',
    keyTopics: ['Prevention strategies', 'Nasal care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Nasa raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Nasal health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 16,
    title: 'Uttarasthana - Mukha Roga',
    sanskritTitle: 'उत्तरस्थान - मुखरोग',
    description: 'Oral diseases and their management.',
    keyTopics: ['Oral anatomy', 'Types of oral diseases', 'Diagnosis', 'Treatment protocols', 'Dental care'],
    keyVerses: ['Mukha roga...', 'Danta roga...'],
    clinicalApplications: ['Oral disease management', 'Dental care', 'ENT procedures'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 17,
    title: 'Uttarasthana - Mukha Roga',
    sanskritTitle: 'उत्तरस्थान - मुखरोग',
    description: 'Specific oral conditions and treatments.',
    keyTopics: ['Danta roga', 'Mukha Pidika', 'Gingivitis', 'Other conditions', 'Treatment protocols'],
    keyVerses: ['Mukha roga chikitsa...', 'Danta roga chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 18,
    title: 'Uttarasthana - Mukha Roga',
    sanskritTitle: 'उत्तरस्थान - मुखरोग',
    description: 'Herbal formulations for oral diseases.',
    keyTopics: ['Dantadhavana', 'Khadiradi', 'Trikantaka', 'Other formulations', 'Administration methods'],
    keyVerses: ['Mukha aushadha...', 'Danta aushadha...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 19,
    title: 'Uttarasthana - Mukha Roga',
    sanskritTitle: 'उत्तरस्थान - मुखरोग',
    description: 'Prevention and care of oral health.',
    keyTopics: ['Prevention strategies', 'Oral hygiene', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Mukha raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Oral health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 20,
    title: 'Uttarasthana - Shiro Roga',
    sanskritTitle: 'उत्तरस्थान - शिरोरोग',
    description: 'Head diseases and their management.',
    keyTopics: ['Head anatomy', 'Types of head diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Shiro roga...', 'Shirahshula...'],
    clinicalApplications: ['Head disease management', 'Neurology', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 21,
    title: 'Uttarasthana - Shiro Roga',
    sanskritTitle: 'उत्तरस्थान - शिरोरोग',
    description: 'Specific head conditions and treatments.',
    keyTopics: ['Shirahshula', 'Pakshaghata', 'Ardita', 'Other conditions', 'Treatment protocols'],
    keyVerses: ['Shiro roga chikitsa...', 'Shirahshula chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 22,
    title: 'Uttarasthana - Shiro Roga',
    sanskritTitle: 'उत्तरस्थान - शिरोरोग',
    description: 'Herbal formulations for head diseases.',
    keyTopics: ['Nasya preparations', 'Taila preparations', 'Kalka', 'Other formulations', 'Administration methods'],
    keyVerses: ['Shiro aushadha...', 'Nasya...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 23,
    title: 'Uttarasthana - Shiro Roga',
    sanskritTitle: 'उत्तरस्थान - शिरोरोग',
    description: 'Prevention and care of head health.',
    keyTopics: ['Prevention strategies', 'Head care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Shiro raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Head health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 24,
    title: 'Uttarasthana - Hrid Roga',
    sanskritTitle: 'उत्तरस्थान - हृद्रोग',
    description: 'Heart diseases and their management.',
    keyTopics: ['Heart anatomy', 'Types of heart diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Hrid roga...', 'Hridshula...'],
    clinicalApplications: ['Heart disease management', 'Cardiology', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 25,
    title: 'Uttarasthana - Hrid Roga',
    sanskritTitle: 'उत्तरस्थान - हृद्रोग',
    description: 'Specific heart conditions and treatments.',
    keyTopics: ['Hridshula', 'Hridgata Vata', 'Other conditions', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Hrid roga chikitsa...', 'Hridshula chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 26,
    title: 'Uttarasthana - Hrid Roga',
    sanskritTitle: 'उत्तरस्थान - हृद्रोग',
    description: 'Herbal formulations for heart diseases.',
    keyTopics: ['Arjuna', 'Arjunarishta', 'Other formulations', 'Administration methods', 'Dosage guidelines'],
    keyVerses: ['Hrid aushadha...', 'Arjuna...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 27,
    title: 'Uttarasthana - Hrid Roga',
    sanskritTitle: 'उत्तरस्थान - हृद्रोग',
    description: 'Prevention and care of heart health.',
    keyTopics: ['Prevention strategies', 'Heart care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Hrid raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Heart health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 28,
    title: 'Uttarasthana - Yakrit Roga',
    sanskritTitle: 'उत्तरस्थान - यकृत्प्लीहरोग',
    description: 'Liver and spleen diseases and their management.',
    keyTopics: ['Liver anatomy', 'Spleen anatomy', 'Types of diseases', 'Diagnosis', 'Treatment protocols'],
    keyVerses: ['Yakrit roga...', 'Pliha roga...'],
    clinicalApplications: ['Liver disease management', 'Spleen care', 'Hepatology'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 29,
    title: 'Uttarasthana - Yakrit Roga',
    sanskritTitle: 'उत्तरस्थान - यकृत्प्लीहरोग',
    description: 'Specific liver and spleen conditions and treatments.',
    keyTopics: ['Yakrit vikara', 'Pliha vikara', 'Other conditions', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Yakrit roga chikitsa...', 'Pliha roga chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 30,
    title: 'Uttarasthana - Yakrit Roga',
    sanskritTitle: 'उत्तरस्थान - यकृत्प्लीहरोग',
    description: 'Herbal formulations for liver and spleen diseases.',
    keyTopics: ['Yakrit plihaghna formulations', 'Other herbs', 'Administration methods', 'Dosage guidelines', 'Monitoring'],
    keyVerses: ['Yakrit aushadha...', 'Pliha aushadha...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 31,
    title: 'Uttarasthana - Yakrit Roga',
    sanskritTitle: 'उत्तरस्थान - यकृत्प्लीहरोग',
    description: 'Prevention and care of liver health.',
    keyTopics: ['Prevention strategies', 'Liver care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Yakrit raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Liver health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 32,
    title: 'Uttarasthana - Mutra Roga',
    sanskritTitle: 'उत्तरस्थान - मूत्ररोग',
    description: 'Urinary diseases and their management.',
    keyTopics: ['Urinary anatomy', 'Types of urinary diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Mutra roga...', 'Mutraghata...'],
    clinicalApplications: ['Urinary disease management', 'Nephrology', 'Surgical interventions'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 33,
    title: 'Uttarasthana - Mutra Roga',
    sanskritTitle: 'उत्तरस्थान - मूत्ररोग',
    description: 'Specific urinary conditions and treatments.',
    keyTopics: ['Mutraghata', 'Ashmari', 'Other conditions', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Mutra roga chikitsa...', 'Mutraghata chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 34,
    title: 'Uttarasthana - Mutra Roga',
    sanskritTitle: 'उत्तरस्थान - मूत्ररोग',
    description: 'Herbal formulations for urinary diseases.',
    keyTopics: ['Gokshura', 'Punarnava', 'Other formulations', 'Administration methods', 'Dosage guidelines'],
    keyVerses: ['Mutra aushadha...', 'Gokshura...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 35,
    title: 'Uttarasthana - Mutra Roga',
    sanskritTitle: 'उत्तरस्थान - मूत्ररोग',
    description: 'Prevention and care of urinary health.',
    keyTopics: ['Prevention strategies', 'Urinary care', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Mutra raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Urinary health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 36,
    title: 'Uttarasthana - Purusha Roga',
    sanskritTitle: 'उत्तरस्थान - पुरुषरोग',
    description: 'Male reproductive diseases and their management.',
    keyTopics: ['Male anatomy', 'Types of male diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Purusha roga...', 'Shukra vikara...'],
    clinicalApplications: ['Male health management', 'Reproductive care', 'Andrology'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 37,
    title: 'Uttarasthana - Purusha Roga',
    sanskritTitle: 'उत्तरस्थान - पुरुषरोग',
    description: 'Specific male conditions and treatments.',
    keyTopics: ['Shukra vikara', 'Klaibya', 'Other conditions', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Purusha roga chikitsa...', 'Shukra vikara chikitsa...'],
    clinicalApplications: ['Specific treatments', 'Clinical protocols', 'Patient management'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 38,
    title: 'Uttarasthana - Purusha Roga',
    sanskritTitle: 'उत्तरस्थान - पुरुषरोग',
    description: 'Herbal formulations for male diseases.',
    keyTopics: ['Vajikarana formulations', 'Other herbs', 'Administration methods', 'Dosage guidelines', 'Monitoring'],
    keyVerses: ['Purusha aushadha...', 'Vajikarana...'],
    clinicalApplications: ['Herb selection', 'Formulation choice', 'Treatment protocols'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 39,
    title: 'Uttarasthana - Purusha Roga',
    sanskritTitle: 'उत्तरस्थान - पुरुषरोग',
    description: 'Prevention and care of male health.',
    keyTopics: ['Prevention strategies', 'Male health', 'Diet guidelines', 'Lifestyle modifications', 'Research directions'],
    keyVerses: ['Purusha raksha...', 'Prevention...'],
    clinicalApplications: ['Preventive care', 'Male health', 'Patient education'],
  },
  {
    sthana: 'Uttarasthana',
    sthanaNumber: 6,
    chapterNumber: 40,
    title: 'Uttarasthana - Stri Roga',
    sanskritTitle: 'उत्तरस्थान - स्त्रीरोग',
    description: 'Female reproductive diseases and their management.',
    keyTopics: ['Female anatomy', 'Types of female diseases', 'Diagnosis', 'Treatment protocols', 'Surgical procedures'],
    keyVerses: ['Stri roga...', 'Yoni vikara...'],
    clinicalApplications: ['Female health management', 'Reproductive care', 'Gynecology'],
  },
];

export function searchAshtangaHridaya(query: string): AshtangaChapter[] {
  const q = query.toLowerCase();
  return ASHTANGA_CHAPTERS.filter(ch =>
    ch.title.toLowerCase().includes(q) ||
    ch.sanskritTitle.includes(q) ||
    ch.description.toLowerCase().includes(q) ||
    ch.keyTopics.some(t => t.toLowerCase().includes(q)) ||
    ch.keyVerses.some(v => v.toLowerCase().includes(q)) ||
    ch.clinicalApplications.some(a => a.toLowerCase().includes(q))
  );
}

export function getAshtangaChapter(sthana: string, chapter: number): AshtangaChapter | undefined {
  return ASHTANGA_CHAPTERS.find(ch => ch.sthana === sthana && ch.chapterNumber === chapter);
}

export function getAshtangaChaptersBySthana(sthana: string): AshtangaChapter[] {
  return ASHTANGA_CHAPTERS.filter(ch => ch.sthana === sthana);
}

export function getAllAshtangaChapters(): AshtangaChapter[] {
  return ASHTANGA_CHAPTERS;
}
